### ISSUE TITLE
Limited number of videos

### ISSUE THREAD

**Issue by jimijoop** [mattwright324/youtube-metadata#157]
Hi. It's me or there's now a limit of the number of videos we could get? I always get 50 videos no matter the location and timeframe. Such thing didn't happened until recently. It's a bug or it's permanment?

**Comment by mattwright324** [comment]
Hi @jimijoop 

It comes and goes but there isn't much I can do about it. I implemented rate limiting in the Google Dev Console because someone was using up all the API quota for the day in an extremely short time, some sort of bot or automation. The rate limiting worked so that the tool was functional for most people. However, it appears that the person/bot does not stop and their usage results in only the first page of results (50) to come back then any further pages to error.

**Comment by mattwright324** [comment]
Seems like this subsided for the metadata bulk page at some point though sometimes it comes back, still can't do much about it but I restrict the rate limit when I notice high automated usage. My geofind tool though seems to always be affected though and only ever returns 50 results per search or errors.
