### ISSUE TITLE
Can increase jump query

### ISSUE THREAD

**Issue by heiyutian** [mattwright324/youtube-metadata#24]
I saw a video on youtube, Want to by extending the jump, such as https://www.youtube.com/watch?v=aGl5ZhlwOeg  Then jump to https://mattw.io/youtube-metadata/https:// www.youtube.com/watch?v=aGl5ZhlwOeg  The video data is obtained in this way

**Comment by mattwright324** [comment]
I'm not sure what you are asking, a way to go straight from youtube to metadata without having to copy/paste the url? 

I have thought a little about that before. To do that I would need to make something new, browser extension(s).

**Comment by heiyutian** [comment]
> I'm not sure what you are asking, a way to go straight from youtube to metadata without having to copy/paste the url?
> 
> I have thought a little about that before. To do that I would need to make something new, browser extension(s).

I have an extension, can forward the URL to other places, I want to forward it directly to your URL directly, such as forward https://www.youtube.com/watch?v=agl5zhlwoe to https://mattw.io/youtube-metadata/https://www.youtube.com/watch?v=aGl5ZhlwOeg 
But will appear 404 File Not Found
But will appear 404 File Not Found
I hope your URL supports additional https://mattw.io/youtube-metadata/https://www.youtube.com/watch?v=aGl5ZhlwOeg later 
Don't "404File not found"
Don't "404File not found"

**Comment by mattwright324** [comment]
Well for this forwarding extension you are using, you can forward in that way if you include the `submit` and `url` parameters

https://mattw.io/youtube-metadata?submit=true&url=

However, one caveat is that you would need to encode the url for it to work properly. For example:

Unencoded, this will not work because the link itself contains query characters `?` and `=`
https://mattw.io/youtube-metadata?submit=true&url=https://www.youtube.com/watch?v=aGl5ZhlwOeg

Encoded, this will work
https://mattw.io/youtube-metadata/?submit=true&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DaGl5ZhlwOeg

In JavaScript this would be the [`encodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) function.

Alternatively, the shortcut YouTube link without query characters works too and does not need encoding.
https://mattw.io/youtube-metadata/?submit=true&url=https://youtu.be/aGl5ZhlwOeg

**Comment by heiyutian** [comment]
> 对于您正在使用的此转发扩展，如果您包含`submit`和`url`参数，则可以通过这种方式转发
> 
> https://mattw.io/youtube-metadata?submit=true&url=
> 
> 但是，需要注意的是，您需要对url进行编码才能使其正常工作。例如：
> 
> 未经编码，这将不起作用，因为链接本身包含查询字符`?`和`=`
> https://mattw.io/youtube-metadata?submit=true&url=https://www.youtube.com/watch?v=aGl5ZhlwOeg
> 
> 编码后，它将可以使用
> https://mattw.io/youtube-metadata/?submit=true&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DaGl5ZhlwOeg
> 
> 在JavaScript中，这就是[`encodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI)功能。
> 
> 另外，没有查询字符的快捷YouTube链接也可以使用，不需要编码。
> https://mattw.io/youtube-metadata/?submit=true&url=https://youtu.be/aGl5ZhlwOeg

I am not a programmer, I can't modify the extension, let it support the encoding, it seems that this way has to give up

**Comment by heiyutian** [comment]
> Well for this forwarding extension you are using, you can forward in that way if you include the `submit` and `url` parameters
> 
> https://mattw.io/youtube-metadata?submit=true&url=
> 
> However, one caveat is that you would need to encode the url for it to work properly. For example:
> 
> Unencoded, this will not work because the link itself contains query characters `?` and `=`
> https://mattw.io/youtube-metadata?submit=true&url=https://www.youtube.com/watch?v=aGl5ZhlwOeg
> 
> Encoded, this will work
> https://mattw.io/youtube-metadata/?submit=true&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DaGl5ZhlwOeg
> 
> In JavaScript this would be the [`encodeURI()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI) function.
> 
> Alternatively, the shortcut YouTube link without query characters works too and does not need encoding.
> https://mattw.io/youtube-metadata/?submit=true&url=https://youtu.be/aGl5ZhlwOeg

I am not a programmer, I can't modify the extension, let it support the encoding, it seems that this way has to give up
