### ISSUE TITLE
Bulk-channel unavailable.json data is empty

### ISSUE THREAD

**Issue by oplle** [mattwright324/youtube-metadata#94]
https://mattw.io/youtube-metadata/bulk?submit=true&url=https://www.youtube.com/channel/UCFPFMKTwH-uvHvdbAQONwkQ
This channel has 2 unavailable videos, but the unavailable.json data file is empty
This feature is very good, I want to find the content of the regional restriction in YouTube. grateful

**Comment by mattwright324** [comment]
Hi @oplle 

Did you submit the channel with the inspect created playlists option? When using that there appears to be 4 unavailable videos and I was able to export and see that data in the unavailable.json file. Currently playlists are the best option to find unlisted and unavailable videos though I hope to have another source in the future that doesn't rely on playlists.

https://mattw.io/youtube-metadata/bulk?url=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCFPFMKTwH-uvHvdbAQONwkQ&createdPlaylists=true&submit=true

**Comment by mattwright324** [comment]
Well, now that I look at it, they are technically still available because they come back in the API. The two I see you are referring to are in the main videos table, you need to add the region restriction column to the table. There are two videos that are blocked worldwide (249 countries).

![image](https://user-images.githubusercontent.com/7717432/151369097-117f8ed3-3988-4fa5-aeec-a74d424e5b0a.png)

On the left you can click the metadata icon to view the metadata for those specific blocked ones. The `More` section will provide links that may help find the original video.

https://mattw.io/youtube-metadata/?submit=true&url=https://youtu.be/FBv0GT8sua0
https://mattw.io/youtube-metadata/?submit=true&url=https://youtu.be/WsHFKDHjPxM

![image](https://user-images.githubusercontent.com/7717432/151369775-7cda446e-866a-4bf6-99be-bca2b2fc4b8b.png)

**Comment by mattwright324** [comment]
In the context of this app, `unavailable` means private or deleted. A region restriction isn't private or deleted in the api and you can still query details about the video. A region restriction count of 249 countries means worldwide and means you can't watch it anywhere. I currently don't know if its possible to get around a 249 block. Its possible to get around a block with a number less than 249 if a VPN has an allowed country in its list. So those videos would appear in the `videos.json` and `videos.csv` and not `unavailable.json`.
